import java.nio.file.Files
import java.nio.file.Paths
import java.util.stream.Collectors.joining

// Before run this script, download JIS0208-Unicode table by:
// wget https://unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT


val table = Files.readAllLines(Paths.get("JIS0208.TXT"))
    .stream()
    .filter { s -> !s.startsWith("#") }
    .filter { s -> s.contains("<CJK>") }  // Filters CJK letters
    .map { s ->
        val unicode = s.split("\t")[2].substring(2) // third column is a unicode hex codepoint; drop "0x" prefix
        """"\u${unicode}""""
    }
    .collect(joining(","))

val file = """
    // This file is generated by generate-jis0208.kts scirpt.
    
    package rip.deadcode.jppass
    
    val jis0208 = listOf(
        ${table}
    )
""".trimIndent()

Files.writeString(Paths.get("src/main/kotlin/rip/deadcode/jppass/jis0208.kt"), file)
